#!/usr/bin/env python3
"""
gen-bootstrap.py — generates BOOTSTRAP.md with current session state.

Run this every 30 minutes via cron so new sessions always open with
fresh context. BOOTSTRAP.md is auto-injected into the session and deleted
by the agent on startup (per AGENTS.md).

Setup:
  1. Customise the CONFIG section below for your project.
  2. Add to crontab:
       */30 * * * * cd /path/to/workspace && python3 automation/gen-bootstrap.py >> /tmp/gen-bootstrap.log 2>&1
  3. Optionally add a prod health check URL (or leave blank to skip).
"""

import json
import os
import subprocess
from datetime import datetime, timezone, timedelta

# ── CONFIG ──────────────────────────────────────────────────────────────────
WORKSPACE       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRINT_JSON     = os.path.join(WORKSPACE, "workflow/sprint.json")
BOOTSTRAP_OUT   = os.path.join(WORKSPACE, "BOOTSTRAP.md")
PROD_URL        = ""          # e.g. "https://yourdomain.com" — blank to skip health check
UTC_OFFSET_HRS  = 11          # your local timezone offset (hours ahead of UTC)
# ────────────────────────────────────────────────────────────────────────────

LOCAL_OFFSET = timedelta(hours=UTC_OFFSET_HRS)


def local_date() -> str:
    return (datetime.now(timezone.utc) + LOCAL_OFFSET).strftime("%Y-%m-%d")


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def load_sprint() -> dict:
    try:
        with open(SPRINT_JSON) as f:
            return json.load(f)
    except Exception:
        return {}


def active_epics(sprint: dict) -> list[dict]:
    """Extract active/in_progress epics from all sprint arrays."""
    results = []

    def _process(epic: dict, stories_key: str = "items"):
        if epic.get("status") not in ("active", "in_progress"):
            return
        pending = [
            i for i in epic.get(stories_key, [])
            if i.get("status") not in ("done", "delivered", "skipped")
        ]
        results.append({
            "id":      epic.get("id", epic.get("epicId", "")),
            "title":   epic.get("title", epic.get("name", "")),
            "status":  epic.get("status", ""),
            "pending": pending,
        })

    for epic in sprint.get("epics", []):
        _process(epic)
    for epic in sprint.get("pendingEpics", []):
        _process(epic, stories_key="stories")
    for epic in sprint.get("activeEpics", []):
        _process(epic)

    return results


def prod_health() -> str | None:
    if not PROD_URL:
        return None
    try:
        result = subprocess.run(
            ["curl", "-sk", "-o", "/dev/null", "-w", "%{http_code}", PROD_URL],
            capture_output=True, text=True, timeout=8
        )
        code = result.stdout.strip()
        return f"{code} ({'✅' if code == '200' else '🚨 CHECK NOW'})"
    except Exception:
        return "timeout"


def read_memory_blockers() -> list[str]:
    """Try to extract blocked items from today's memory file."""
    date = local_date()
    memory_path = os.path.join(WORKSPACE, "memory", f"{date}.md")
    blockers = []
    try:
        with open(memory_path) as f:
            for line in f:
                line = line.strip()
                if "block" in line.lower() and line.startswith("-"):
                    blockers.append(line)
    except Exception:
        pass
    return blockers[:6]  # cap at 6


def main():
    now = utc_now()
    sprint = load_sprint()
    epics  = active_epics(sprint)
    health = prod_health()

    lines = [
        f"# Session State — {now}",
        "",
        "> Auto-generated by gen-bootstrap.py. Read this, then delete this file (per AGENTS.md).",
        "",
    ]

    # Active sprint
    if epics:
        lines.append("## Active Sprint")
        for epic in epics:
            lines.append(f"- **{epic['id']}** ({epic['status']}): {epic['title']}")
            for item in epic["pending"][:5]:
                iid   = item.get("id", "")
                title = item.get("title", item.get("name", ""))
                st    = item.get("status", "todo")
                lines.append(f"  - {iid} `{st}`: {title}")
        lines.append("")
    else:
        lines += ["## Active Sprint", "- No active epics.", ""]

    # Blockers from memory
    blockers = read_memory_blockers()
    if blockers:
        lines.append("## Blockers (from today's memory)")
        lines.extend(blockers)
        lines.append("")

    # Infra
    lines.append("## Infra")
    if health:
        lines.append(f"- Prod ({PROD_URL}): {health}")
    lines += [
        "- Check `openclaw gateway status` if channels are unresponsive.",
        "",
    ]

    lines.append(f"_Generated at {now} — delete this file after reading._")

    with open(BOOTSTRAP_OUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[gen-bootstrap] Written BOOTSTRAP.md ({len(lines)} lines) at {now}")


if __name__ == "__main__":
    main()
